// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-8mtVJLGEoVRY-zqqRL6saxwJQgqPRJw',
    appId: '1:881499263846:android:af7ff2aefdff3f83dcaea7',
    messagingSenderId: '881499263846',
    projectId: 'medoptic-85ad0',
    databaseURL: 'https://medoptic-85ad0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medoptic-85ad0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkfh2hU755SUa-IpqPyIWkLSN8zMazNe4',
    appId: '1:881499263846:ios:1a7d544501b7a5f0dcaea7',
    messagingSenderId: '881499263846',
    projectId: 'medoptic-85ad0',
    databaseURL: 'https://medoptic-85ad0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'medoptic-85ad0.appspot.com',
    iosClientId: '881499263846-tnroo4kfpk2e99er9j23ujhos1k0d4ii.apps.googleusercontent.com',
    iosBundleId: 'com.example.medoptic',
  );
}
